routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeContoller;
use App\Http\Controllers\AdminDashboardController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\ProfileController;
use Illuminate\Contracts\Cache\Store;
use Laravel\Socialite\Facades\Socialite;
use App\Http\Controllers\CompanyProfileController;
use App\Http\Controllers\DesignationController;
use App\Http\Controllers\CompanyEmployeeController;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\HomeController;


use function PHPUnit\Framework\fileExists;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/show/{id}', [HomeController::class, 'show'])->name('companyshow');
Auth::routes();
Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::group(['middleware' => ['auth', 'role:company-admin']], function() {
    

    Route::get('company_admin/profile', [CompanyProfileController::class, 'index'])->name('company.profile');
    Route::put('company_admin/profile/{id}/update', [CompanyProfileController::class, 'update'])->name('profile.update');
    Route::get('company_admin/employees', [CompanyEmployeeController::class, 'employeelist'])->name('company.employee');

});

Route::group(['middleware' => ['auth', 'role:super-admin']], function() {
    Route::get('/profile/edit', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile/update', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/admin', [AdminDashboardController::class, 'dashboardData'])->name('superadmin');;
    Route::resource('/companies', CompanyController::class);
    Route::resource('/employees', EmployeeContoller::class);
    Route::resource('/designations', DesignationController::class);
    Route::put('/employees/{employee}/status', [EmployeeContoller::class, 'updateStatus'])->name('employees.updateStatus');
    });
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');    

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/employeelist.blade.php
@extends('layout.compantadminmaster')
@section('title', 'Manage Company')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Manage Employee</h1>
        <div class="row">
            <div class="add-btn col-md-11">
            </div>
            {{-- <div class="add-btn col-md-1">
                <a href="{{ route('employees.create') }}"><button class="btn btn-dark pull-right">ADD <i class="fa fa-plus"></i></button></a>    
            </div> --}}
        </div>
        <div class="card mb-4 mt-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Firstname</th>
                                <th>Lastname</th>
                                <th>email</th>
                                <th>company</th>
                                <!-- <th>status</th> -->
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach($employees as $item)
                            <tr>
                                <td>{{ $item->firstname }}</td>
                                <td>{{ $item->lastname }}</td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->company->name }}</td>
                                <!-- <td class="text-center">
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" id="status-{{ $item->id }}" data-id="{{ $item->id }}" {{ $item->status == 1 ? 'checked' : '' }}>
                                    <label class="custom-control-label" for="status-{{ $item->id }}"></label>
                                </div>
                                </td> -->
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Scripts section -->
@push('scripts')
<script>
    $(document).ready(function() {
        console.log("dhdhdhdh");
        // Handle toggle change event
        
    });
</script>
@endpush
@endsection

resources/views/frontpage.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Upskill - @yield('title')</title>
    <link href="{{ asset('public/dist/css/styles.css') }}" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css">
</head>

<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url('admin') }}">Frontend</a>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        <!-- <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
            </div>
        </div> -->
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ml-auto ml-md-0">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                <a href="{{ url('login') }}" class="dropdown-item"><i class="fas fa-user"></i> Login</a>
            </div>
        </li>
    </ul>
</nav>
<main class="mt-5">
    <div class="container-fluid mt-5">
        <h1 class="mt-4">view Company</h1>
        <div class="row">
            <div class="add-btn col-md-11">
            </div>
            <div class="add-btn col-md-1 pull-right">
                <a href="{{ route('companies.create') }}"><button class="btn btn-dark pull-right">ADD <i class="fa fa-plus"></i></button></a>
            </div>
        </div>
        <div class="card mb-4 mt-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Logo</th>
                                <th>Email</th>
                                <th>Website</th>
                                <th>View</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($company as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td class="text-center">
                                    <a href="{{ asset("public/storage/company_logos") . "/" . $item->logo }}" data-fancybox="gallery"><img src="{{ asset("public/storage/company_logos") . "/" . $item->logo }}" alt="img" height="80px" width="80px" style="border-radius: 50%;"  class="logo-img"></a>
                                    </td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->website }}</td>
                                <td class="text-center">
                                    <a href="{{ route('companyshow',$item->id) }}" title="Edit Student"><button class="btn btn-primary btn-sm"><i class="fa fa-eye" aria-hidden="true"></i> view</button></a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
<script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="{{ asset('public/dist/js/scripts.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="{{ asset('public/dist/assets/demo/chart-area-demo.js') }}"></script>
    <script src="{{ asset('public/dist/assets/demo/chart-bar-demo.js') }}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="{{ asset('public/dist/assets/demo/datatables-demo.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script>
        @if(session('status'))
        swal({
            title: '{{ session('
            statusCode ') }} ',
            text: '{{ session('
            status ') }}',
            icon: "success",
            button: "okay",
        });
        @endif
        $(document).ready(() => {
            $("#logo").change(function() {
                const file = this.files[0];
                if (file) {
                    let reader = new FileReader();
                    reader.onload = function(event) {
                        $("#preview")
                            .attr("src", event.target.result);
                    };
                    reader.readAsDataURL(file);
                }
            });
        });
        document.querySelectorAll('.delete').forEach(button => {
            button.addEventListener('click', function(e) {
                e.preventDefault(); // Prevent the form from submitting immediately
                // Ask for confirmation before deleting
                swal({
                        title: "Are you sure?",
                        text: "Once deleted, you will not be able to recover this Record!",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                    .then((willDelete) => {
                        if (willDelete) {
                            let formId = this.closest('form').getAttribute('id');
                            console.log(formId)

                            document.getElementById(formId).submit();
                            swal("Poof! Your Recrod has been deleted!", {
                                icon: "success",
                            });
                        } else {
                            swal("Your Record is safe!");
                        }
                    });
            });
        });


        //Ajax call of employees status
        $('input[type="checkbox"]').change(function() {
            var employeeId = $(this).data('id');
            var status = $(this).prop('checked') ? 1 : 0;
            console.log(status);
            console.log("hheheh");
            $.ajax({
                url: '/employees/' + employeeId + '/status',
                type: 'POST',
                data: {
                    _method: 'PUT',
                    _token: '{{ csrf_token() }}',
                    status: status
                },
                success: function(response) {
                    swal({
                        title: response.message,
                        text: response.message,
                        icon: "success",
                        button: "okay",
                    });
                },
                error: function(xhr) {
                    swal({
                        title: "status does not updated something went wrong",
                        text: "status does not updated something went wrong",
                        icon: "danger",
                        button: "okay",
                    });
                }
            });
        });
    </script>
</body>
</html>

resources/views/index.blade.php
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>all cards</h1>
</body>
</html>

resources/views/manageCompany.blade.php
@extends('layout.master')
@section('title', 'Manage Company')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Manage Company</h1>
        <div class="card mb-4">
            <div class="card-body">
                @if(isset($company))
                <form action="{{ route('companies.update', $company->id) }}" method="post" enctype="multipart/form-data">
                    @method('put')
                    @else
                    <form action="{{ url('companies') }}" method="post" enctype="multipart/form-data">
                        @endif
                        @csrf
                        <div class="form-group">
                            <label>Name <span class="text-danger">*</span></label>
                            <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name" value="{{ old('name', $company->name ?? '') }}">
                            <span class="text-danger">@error('name') {{ $message }} @enderror</span>
                        </div>
                        <div class="form-group">
                            <label>Email <span class="text-danger">*</span></label>
                            <input type="email" name="email" id="email" class="form-control" placeholder="abc@gmail.com" value="{{ old('email', $company->email ?? '') }}">
                            <span class="text-danger">@error('email') {{ $message }} @enderror</span>
                        </div>
                        <fieldset style="border: 1px solid #ccc; padding: 20px; margin-bottom: 20px;">
                            <legend style="font-weight: bold; padding: 0 10px;">Login Detail Section</legend>

                            <div class="form-group">
                                <label for="loginEmail">Login Email <span class="text-danger">*</span></label>
                                <input type="email" name="loginEmail" id="loginEmail" class="form-control" placeholder="abc@gmail.com" value="{{ old('loginEmail', $company->loginEmail ?? '') }}">
                                <span class="text-danger">@error('loginEmail') {{ $message }} @enderror</span>
                            </div>

                            <div class="form-group">
                                <label for="password">Password <span class="text-danger">*</span></label>
                                <input type="password" name="password" id="password" class="form-control" placeholder="Enter password">
                                <span class="text-danger">@error('password') {{ $message }} @enderror</span>
                            </div>
                        </fieldset>

                        <div class="form-group">
                            <label>Website <span class="text-danger">*</span></label>
                            <input type="text" name="website" id="website" class="form-control" placeholder="www.abc.com" value="{{ old('website', $company->website ?? '') }}">
                            <span class="text-danger">@error('website') {{ $message }} @enderror</span>
                        </div>
                        <div class="form-group">
                            <label>Contact Number<span class="text-danger">*</span></label>
                            <input type="number" name="contactNumber" id="contactNumber" class="form-control" placeholder="1234567890" value="{{ old('contactNumber', $company->contactNumber ?? '') }}">
                            <span class="text-danger">@error('contactNumber') {{ $message }} @enderror</span>
                        </div>
                        <div class="form-group">
                            <label>Company Details</label>
                            <textarea name="companyDetails" id="companyDetails" class="form-control" placeholder="Enter company details">{{ old('companyDetails', $company->companyDetails ?? '') }}</textarea>
                            <span class="text-danger">@error('companyDetails') {{ $message }} @enderror</span>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label class="col-sm-1">Upload Logo <span class="text-danger">*</span></label>
                                <input type="file" name="logo" id="logo" class="form-control col-md-3">
                                @if (isset($company))
                                <input name="oldlogo" type="hidden" value="{{ $company->logo }}">
                                <img src="{{ asset('public/storage/company_logos/' . $company->logo) }}" id="preview" alt="img" height="100px" width="40px" class="col-sm-1 border border-dark ml-4">
                                @else
                                <img src="{{ asset('public/nopreview.png') }}" alt="img" id="preview" height="100px" width="40px" class="col-sm-1 border border-dark ml-4">
                                @endif
                            </div>
                            <span class="text-danger">@error('logo') {{ $message }} @enderror</span>
                        </div>
                        <input type="submit" value="Save" class="btn btn-success">
                    </form>
            </div>
        </div>
    </div>
</main>
<script src="https://cdn.ckeditor.com/4.17.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('companyDetails');
</script>
@endsection

resources/views/manageDesignations.blade.php
@extends('layout.master')
@section('title', 'Manage Designation')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Manage Designation</h1>
        <div class="card mb-4">
            <div class="card-body">
                @if(isset($designations))
                    <form action="{{ route('designations.update', $designations->id) }}" method="post" enctype="multipart/form-data">
                        @method('put')
                @else
                    <form action="{{ url('designations') }}" method="post" enctype="multipart/form-data">
                @endif 
                    @csrf
                    <div class="form-group">
                        <label>Designation Name <span class="text-danger">*</span></label>
                        <input type="text" name="designation_name" id="designation_name" class="form-control" placeholder="Enter Designation Name" value="{{ old('designation_name', $designations->designation_name ?? '') }}">
                        <span class="text-danger">@error('designation_name') {{ $message }} @enderror</span>
                    </div>
                    <div class="form-group">
                        <label>Description </label>
                        <input type="text" name="description" id="description" class="form-control" placeholder="Enter Description" value="{{ old('description', $designations->description ?? '') }}">
                        <span class="text-danger">@error('description') {{ $message }} @enderror</span>
                    </div>
                    <input type="submit" value="Save" class="btn btn-success">
                </form>
            </div>
        </div>
    </div>
</main>
@endsection

resources/views/viewCompany.blade.php
@extends('layout.master')
@section('title', 'Manage Company')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">view Company</h1>
        <div class="row">
            <div class="add-btn col-md-11">
            </div>
            <div class="add-btn col-md-1 pull-right">
                <a href="{{ route('companies.create') }}"><button class="btn btn-dark pull-right">ADD <i class="fa fa-plus"></i></button></a>
            </div>
        </div>
        <div class="card mb-4 mt-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Logo</th>
                                <th>Email</th>
                                <th>Website</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($company as $item)
                            <tr>
                                <td>{{ $item->name }}</td>
                                <td class="text-center">
                                    <a href="{{ asset("public/storage/company_logos") . "/" . $item->logo }}" data-fancybox="gallery"><img src="{{ asset("public/storage/company_logos") . "/" . $item->logo }}" alt="img" height="80px" width="80px" style="border-radius: 50%;"  class="logo-img"></a>
                                    </td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->website }}</td>
                                <td class="text-center">
                                    <a href="{{ route('companies.edit',$item->id) }}" title="Edit Student"><button class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> Edit</button></a>
                                </td>
                                <td class="text-center">
                                    <form method="POST" action="{{ url('companies', $item->id) }}" accept-charset="UTF-8" style="display:inline" id="{{ 'deleteCompany_' . $item->id }}" class="delete">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger btn-sm delete"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
<script>
    
</script>
@endsection

resources/views/viewDesignations.blade.php
@extends('layout.master')
@section('title', 'Manage Designations')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Manage Designations</h1>
        <div class="row">
            <div class="add-btn col-md-11">
            </div>
            <div class="add-btn col-md-1">
                <a href="{{ route('designations.create') }}"><button class="btn btn-dark pull-right">ADD <i class="fa fa-plus"></i></button></a>    
            </div>
        </div>
        <div class="card mb-4 mt-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Designation Name</th>
                                <th>Description</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach($designations as $item)
                            <tr>
                                <td>{{ $item->designation_name }}</td>
                                <td>{{ $item->description }}</td>
                                <td class="text-center">
                                    <a href="{{ route('designations.edit',$item->id) }}" title="Edit Student"><button class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> Edit</button></a>
                                </td>
                                <td class="text-center">
                                    <form method="POST" action="{{ url('designations', $item->id) }}" accept-charset="UTF-8" style="display:inline" id="deleteEmployee">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger btn-sm delete" id="deleteCompany"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Scripts section -->
@push('scripts')
<script>
    $(document).ready(function() {
        console.log("dhdhdhdh");
        // Handle toggle change event
        
    });
</script>
@endpush
@endsection

resources/views/viewEmployee.blade.php
@extends('layout.master')
@section('title', 'Manage Company')
@section('main-content')
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Manage Employee</h1>
        <div class="row">
            <div class="add-btn col-md-11">
            </div>
            <div class="add-btn col-md-1">
                <a href="{{ route('employees.create') }}"><button class="btn btn-dark pull-right">ADD <i class="fa fa-plus"></i></button></a>    
            </div>
        </div>
        <div class="card mb-4 mt-3">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Firstname</th>
                                <th>Lastname</th>
                                <th>email</th>
                                <th>company</th>
                                <th>Designation</th>
                                <th>status</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            @foreach($employees as $item)
                            <tr>
                                <td>{{ $item->firstname }}</td>
                                <td>{{ $item->lastname }}</td>
                                <td>{{ $item->email }}</td>
                                <td>{{ $item->company->name }}</td>
                                <td>{{ $item->designation->designation_name ?? "" }}</td>
                                <td class="text-center">
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" id="status-{{ $item->id }}" data-id="{{ $item->id }}" {{ $item->status == 1 ? 'checked' : '' }}>
                                    <label class="custom-control-label" for="status-{{ $item->id }}"></label>
                                </div>
                                </td>
                                <td class="text-center">
                                    <a href="{{ route('employees.edit',$item->id) }}" title="Edit Student"><button class="btn btn-primary btn-sm"><i class="fa fa-edit" aria-hidden="true"></i> Edit</button></a>
                                </td>
                                <td class="text-center">
                                    <form method="POST" action="{{ url('employees', $item->id) }}" accept-charset="UTF-8" style="display:inline" id="deleteEmployee">
                                        {{ method_field('DELETE') }}
                                        {{ csrf_field() }}
                                        <button type="submit" class="btn btn-danger btn-sm delete" id="deleteCompany"><i class="fa fa-trash" aria-hidden="true"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</main>
<!-- Scripts section -->
@push('scripts')
<script>
    $(document).ready(function() {
        console.log("dhdhdhdh");
        // Handle toggle change event
        
    });
</script>
@endpush
@endsection